# .github/workflows/release-images.yml
name: Release Images

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker_build_push:
    name: Build & Push Images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - name: api-gateway
            file: services/api-gateway/Dockerfile
            context: .
            image: ghcr.io/alvi-noman/muvance-api-gateway
          - name: auth
            file: services/auth-service/Dockerfile
            context: .
            image: ghcr.io/alvi-noman/muvance-auth
          - name: upload
            file: services/upload-service/Dockerfile
            context: .
            image: ghcr.io/alvi-noman/muvance-upload

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Vars
        id: vars
        run: |
          echo "STAMP=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "SHA_FULL=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push ${{ matrix.service.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.file }}
          target: prod                     # build the production stage
          push: true
          platforms: linux/amd64           # add linux/arm64 if you really need multi-arch
          tags: |
            ${{ matrix.service.image }}:prod
            ${{ matrix.service.image }}:${{ steps.vars.outputs.STAMP }}-${{ steps.vars.outputs.SHA_SHORT }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ steps.vars.outputs.SHA_FULL }}
            org.opencontainers.image.title=${{ matrix.service.name }}
            org.opencontainers.image.created=${{ steps.vars.outputs.STAMP }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # OPTIONAL: trigger Render deploy hooks if you add secrets
      - name: Trigger Render deploy (api-gateway)
        if: ${{ success() && secrets.RENDER_DEPLOY_HOOK_API_GATEWAY }}
        run: curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_API_GATEWAY"

      - name: Trigger Render deploy (auth)
        if: ${{ success() && secrets.RENDER_DEPLOY_HOOK_AUTH }}
        run: curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_AUTH"

      - name: Trigger Render deploy (upload)
        if: ${{ success() && secrets.RENDER_DEPLOY_HOOK_UPLOAD }}
        run: curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_UPLOAD"
